[package]
name = "vpn-client"
version = "0.1.0"
edition = "2024"

[dependencies]
defguard_wireguard_rs = "0.7.8"
x25519-dalek = { version = "2", features = ["static_secrets"] }
base64 = "0.22"
env_logger = "0.11"
ctrlc = "3.4"
chrono = "0.4.42"
